refactor: call user belonging to customer contact
registreerocks/registree-core pull request #196
Opened 2020-09-07 08:36 UTC by sabinebertram

resolves #195

2020-09-07 12:52 UTC, longtomjr approved these changes

2020-09-07 12:52 UTC, longtomjr commented on src/contacts/contacts.resolver.ts
> +  constructor(private readonly usersService: ContactsService) {}
usersService is still the name of the injected service's variable

2020-09-07 12:52 UTC, longtomjr commented on src/contacts/contacts.service.ts
> +  async createContact(input: CreateContactInput): Promise<Contact> {
Does this not need to add the contact to the mongo db as well?

2020-09-10 07:33 UTC, sabinebertram commented on src/contacts/contacts.resolver.ts
> +  constructor(private readonly usersService: ContactsService) {}
Thanks for noticing!

2020-09-10 07:34 UTC, sabinebertram commented on src/contacts/contacts.service.ts
> +  async createContact(input: CreateContactInput): Promise<Contact> {
Or should there be a second endpoint to add a contact to a customer?

2020-09-10 08:56 UTC, sabinebertram commented on src/contacts/contacts.service.ts
> +  async createContact(input: CreateContactInput): Promise<Contact> {
done

2020-09-10 09:37 UTC, longtomjr requested changes

2020-09-10 09:37 UTC, longtomjr commented on src/contacts/contacts.service.ts
> +import { ID } from 'aws-sdk/clients/iotsitewise';
Wrong ID import here

2020-09-10 09:37 UTC, longtomjr commented on src/contacts/contacts.service.ts
> +    customerId: ID,
You would want to use `string` here since ID is a graphql scalar type that does not need/have and equivalent typescript type

2020-09-10 09:37 UTC, longtomjr commented on src/customers/customers.service.ts
> +import { ID } from 'aws-sdk/clients/s3';
Same here with this id import

2020-09-10 09:37 UTC, longtomjr commented on src/customers/customers.service.ts
> +  async addContact(customerId: ID, contact: Contact): Promise<Customer> {
`async addContact(customerId: string, contact: Contact): Promise<Customer> {`

2020-09-10 09:42 UTC, longtomjr approved these changes

2020-09-10 09:44 UTC, merged