feat: set student status as viewed on event invite
registreerocks/registree-core pull request #261
Opened 2020-10-13 12:47 UTC by sabinebertram

Just as a note: 
* We also need to restrict the view on other students' invites in the returned EventQuery object.
* Something is off with time zones.

2020-10-19 09:46 UTC, longtomjr requested changes

2020-10-19 09:46 UTC, longtomjr commented on src/queries/queries.service.ts
> +    input['student_address'] = transcriptId;
Don't think it matters here, but I tend to prefer not modifying objects passed in as arguments to a function.
something like this should do the same without modifying the state of the 'input' arg
```
    const response = await this.queryDataService.updateQueryInviteStatus(
      queryId,
      {
        ...input
        'student_address': transcriptId
       },
    );
```

2020-10-19 09:46 UTC, longtomjr commented on src/queries/queries.service.ts
> +      'http://localhost:8001',
I know this is existed, but I am not sure why we have to pass in a URL in this case? Does it matter that we pass in a URL?

2020-10-19 09:46 UTC, longtomjr commented on src/query-data/query-data.service.ts
> +      this.logger.error(
This error code should not me needed anymore with the exception filter we have. We should create a refactor task to clean it up and double check that the errors get logged.

2020-10-21 07:36 UTC, sabinebertram commented on src/queries/queries.service.ts
> +      'http://localhost:8001',
The linking id is a hash of the identifying id and the url, that is why we are passing it. I'm happy to change that because that is also the reason why this endpoint is so incredibly slow. We'll have to re-port on staging, and later on UCT's side, though.

2020-10-21 07:37 UTC, sabinebertram commented on src/query-data/query-data.service.ts
> +      this.logger.error(
I'll create a ticket for it.

2020-10-21 07:38 UTC, longtomjr commented on src/queries/queries.service.ts
> +      'http://localhost:8001',
I think it makes sense to add a task to changes this on both sides to the backlog, and just keep the current way we have it.

2020-10-21 07:44 UTC, longtomjr approved these changes

2020-10-21 07:51 UTC, merged