feat: return auth0 user when customer contacts are queried
registreerocks/registree-core pull request #266
Opened 2020-10-16 09:10 UTC by sabinebertram

I think we have to flush core db in order to make this work since I changed the schema.

2020-10-19 09:56 UTC, longtomjr requested changes

2020-10-19 09:56 UTC, longtomjr commented on src/customers/customers.resolver.ts
> +      customer.contactIds.map(async contactId => {
I think we should look at if there is a way for us to get a bunch of users from auth 0, given a bunch of ids. This will not scale well, and we might run into rate limiting issues as well. If anything, this should do the trick https://auth0.com/docs/api/management/v2/#!/Users/get_users

2020-10-23 07:11 UTC, longtomjr requested changes

2020-10-23 07:11 UTC, longtomjr commented on src/customers/customers.resolver.ts
> +    return `user_id:("${contactIds.join('" OR "')}")`;
This probably makes more sense to move to the data-service layer, since the query string is specifically related to auth0.

2020-10-23 07:12 UTC, sabinebertram commented on src/customers/customers.resolver.ts
> +    return `user_id:("${contactIds.join('" OR "')}")`;
Makes sense

2020-10-23 07:20 UTC, longtomjr approved these changes

2020-10-23 07:20 UTC, merged