feat: check whether student read privacy policy returns boolean
registreerocks/registree-core pull request #303
Opened 2020-11-09 09:54 UTC by sabinebertram

2020-11-09 11:49 UTC, longtomjr requested changes

2020-11-09 11:49 UTC, longtomjr commented on src/schema.graphql
> +  setStudentPrivacyPolicyReadDate: DateTime!
Calling this `acceptPrivacyPolicy` might help make this name a bit shorter and I think it might describe the action better as well.

2020-11-09 11:49 UTC, longtomjr commented on src/schema.graphql
> +  studentHasReadPrivacyPolicyVersion(privacyPolicyVersionDate: DateTime!): Boolean!
I think I would prefer `acceptedPrivacyPolicy` and not passing in any arguments, since the date the privacy policy were accepted by the student is information we can already get in core, and the latest privacy policy is something that we will be able to get in core as well (for now we can hard-code it until we implement #272 ). I don't think we should expect this information from the client-side.

This might even be better in a `me` style query where the user's details and acceptance is a property of. This will allow the front-end to do 1 initial call and get all the data related to the new logged-in user from core.

2020-11-09 12:59 UTC, sabinebertram commented on src/schema.graphql
> +  studentHasReadPrivacyPolicyVersion(privacyPolicyVersionDate: DateTime!): Boolean!
Just to double check, you are saying that we should add a privacy policy attribute to the user and use that to check?

2020-11-11 13:40 UTC, longtomjr approved these changes

2020-11-11 13:59 UTC, merged