feat: add endpoint for auth0 rule
registreerocks/registree-core pull request #310
Opened 2020-11-16 10:47 UTC by sabinebertram

2020-11-16 13:22 UTC, longtomjr requested changes
We need to create a PR for the infrastructure repo as well, and add this variable to the terraform cloud variables before merging, otherwise the deployment will fail.

2020-11-16 13:22 UTC, longtomjr commented on src/auth/rest-auth.middleware.ts
> +    /* eslint-disable */
What is the reason for disabling eslint here?

2020-11-16 13:22 UTC, longtomjr commented on src/auth/rest-auth.middleware.ts
> +      { session: false, failureRedirect: '/api/unauthorized' },
Does this route exist?

2020-11-16 13:22 UTC, longtomjr commented on src/auth/rest-auth.middleware.ts
> +export class RestAuthMiddleware implements NestMiddleware {
This can probably be implemented using a guard instead of middleware. The reason the graphql part is implemented as middleware is because it needs to run before shield to populate the user object on the request context. For this using a guard and only adding it on controller methods that need to check the API key will give us more flexibility.

https://docs.nestjs.com/techniques/authentication should have the docs you need for this implementation with multiple strategies.

2020-11-16 13:22 UTC, longtomjr commented on src/app-config/config/auth.config.ts
> +  const auth0ApiKey = process.env.AUTH0_API_KEY;
Just for completeness, can you add this one to the .env.template as well?

2020-11-17 08:54 UTC, sabinebertram commented on src/auth/rest-auth.middleware.ts
> +export class RestAuthMiddleware implements NestMiddleware {
Will have a look. Thanks!

2020-11-17 08:56 UTC, sabinebertram commented on src/auth/rest-auth.middleware.ts
> +      { session: false, failureRedirect: '/api/unauthorized' },
Good question. I need to investigate.

2020-11-17 09:00 UTC, sabinebertram commented on src/auth/rest-auth.middleware.ts
> +    /* eslint-disable */
I wasn't able to import the type of the return value of `authenticate`. So I disabled it for now.

2020-11-18 08:58 UTC, sabinebertram commented
Depends on [#15](https://github.com/registreerocks/infrastructure/pull/15).

2020-11-23 10:30 UTC, longtomjr approved these changes

2020-11-23 10:54 UTC, merged