Sf rsvps after event5
registreerocks/registree-core pull request #322
Opened 2020-11-30 15:15 UTC by salemandreus

Disallow student from changing RSVP after they have attended event.

(Recreated because the previous PR was to master.)

2020-12-01 06:48 UTC, longtomjr requested changes

2020-12-01 06:48 UTC, longtomjr commented on src/query-data/query-data.service.ts
> +
Please revert this whitespace change

2020-12-01 06:48 UTC, longtomjr commented on src/queries/queries.service.ts
> +            'Not allowed to change invitation rsvp status after attending an event.',
The errors thrown in this try block will be caught by the catch block.

2020-12-01 06:48 UTC, longtomjr commented on src/queries/queries.service.ts
> +      throw new ServerError(
What are you expecting to catch here? I am not sure what the benefit of catching and re-throwing an error here is.

2020-12-01 06:48 UTC, longtomjr commented on src/queries/queries.service.ts
> +      if (invite) {
Please try to refactor this to not have nested conditionals

2020-12-07 21:11 UTC, salemandreus commented on src/queries/queries.service.ts
> +      throw new ServerError(
My reasoning was a more specific error message for logging purposes. Do we have a more elegant way to handle this?

2020-12-07 21:23 UTC, salemandreus commented on src/queries/queries.service.ts
> +            'Not allowed to change invitation rsvp status after attending an event.',
Ah right. I don't know how I missed that. 🤦‍♂️

2020-12-08 07:05 UTC, salemandreus commented on src/queries/queries.service.ts
> +      throw new ServerError(
Also is the server error fine in this case or would we use a different one?

2020-12-08 07:06 UTC, salemandreus commented on src/queries/queries.service.ts
> +            'Not allowed to change invitation rsvp status after attending an event.',
Am moving it out of the block, also is the server error fine in this case or would we use a different one?

2020-12-08 07:26 UTC, longtomjr commented on src/queries/queries.service.ts
> +            'Not allowed to change invitation rsvp status after attending an event.',
I don't think this is a server error, since the action and input is invalid, making it an input or user error. I think the best would be to throw an ApolloError with a relevant error code. Look at `UserInputError`. It should be part of the apollo exports

2020-12-08 07:29 UTC, longtomjr commented on src/queries/queries.service.ts
> +      throw new ServerError(
Our errors are handled up the execution chain and logged. Look at https://github.com/registreerocks/registree-core/blob/staging/src/common/error-context.interceptor.ts and https://github.com/registreerocks/registree-core/blob/staging/src/all-exceptions.filter.ts.

I don't see the need for a try-catch block here at all, since the only expected errors in this try block is the ones being thrown, unless I am missing something.

2020-12-08 12:45 UTC, salemandreus commented on src/queries/queries.service.ts
> +      throw new ServerError(
I was doing that in the case of the object property not being available - turns out that handling is actually accommodated by the existing handling of the query failing in the first case which I think relates to what you are saying here? 
Will remove it.

2020-12-08 13:51 UTC, salemandreus commented on src/queries/queries.service.ts
> +            'Not allowed to change invitation rsvp status after attending an event.',
Have added it.

2020-12-08 14:51 UTC, longtomjr requested changes

2020-12-08 14:51 UTC, longtomjr commented on src/queries/queries.service.ts
> +    const invite = invites.find(x => x.transcriptId === transcriptId);
I think this can be done without instantiating `invites` variable.

2020-12-08 14:51 UTC, longtomjr commented on src/queries/queries.service.ts
> +    const event = await this.getQuery(queryId);
I think renaming this variable to `query` or something similar will make it clearer.

2020-12-08 14:51 UTC, longtomjr commented on src/queries/queries.service.ts
> +      throw new UserInputError('Not allowed to change invitation status.');
This error will not tell the user what is wrong, only that they cannot perform an action.

2020-12-08 14:51 UTC, longtomjr commented on src/queries/queries.service.ts
> +    } else {
I would remove this `else` block since the `if` statement acts as an assertion and throws (so stops the execution of the function).

2020-12-08 18:47 UTC, salemandreus commented on src/queries/queries.service.ts
> +    } else {
Ah, true.

2020-12-09 07:31 UTC, longtomjr commented on src/queries/queries.service.ts
> +        'Not allowed to modify the event invite after the event has already occurred.',
I still think this error does not describe the case. "Not allowed to modify the event invite after the event has been attended" seems to be what is actually happening here or am I mistaken?

2020-12-09 07:40 UTC, salemandreus commented on src/queries/queries.service.ts
> +        'Not allowed to modify the event invite after the event has already occurred.',
True. I was thinking of the intent rather than the specific scenario occurring in this case. Have pushed that change.

2020-12-09 07:41 UTC, longtomjr approved these changes

2020-12-09 07:49 UTC, sabinebertram approved these changes
Looks good to me. We'll deal with test coverage at a later point. Thanks!

2020-12-09 08:05 UTC, merged