When setting the RSVP status for a student on an invite, set the invite to viewed
registreerocks/registree-core pull request #324
Opened 2020-12-10 11:18 UTC by salemandreus

When setting the RSVP status for a student on an invite, set the invite to viewed if not viewed already to prevent bad state.
Task #311

2020-12-10 12:58 UTC, longtomjr requested changes

2020-12-10 12:58 UTC, longtomjr commented on src/queries/queries.service.ts
> +      const viewed = true;
I am not sure why this needs to be declared as a variable

2020-12-10 12:58 UTC, longtomjr commented on src/queries/queries.service.ts
> +      await this.queryDataService.updateQueryInviteStatus(queryId, {
I think that this can be done in a single call, no need to call updateQueryInviteStatus 2 times

2020-12-10 13:03 UTC, salemandreus commented on src/queries/queries.service.ts
> +      await this.queryDataService.updateQueryInviteStatus(queryId, {
This is to ensure it always updates the viewed status if it is null, even if it doesn't allow updating the RSVP, to prevent bad state. Sabine mentioned this last week I believe, that if attended == true then it should also be viewed.

2020-12-10 13:34 UTC, longtomjr commented on src/queries/queries.service.ts
> +      await this.queryDataService.updateQueryInviteStatus(queryId, {
Since this is does network call I think it makes sense to try and eliminate having 2 calls to the same endpoint if possible.

2020-12-11 09:30 UTC, longtomjr commented on src/queries/queries.service.ts
> +        viewed: invite && !invite.viewedAt ? true : undefined,
`!!invite?.viewedAt ? undefined : true` seems to be easier to follow for me. There is probably an even cleaner way to represent this.

note the use of optional chaining
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining

also note that there is a case where the function would be called with a value for `input.viewed` and we should cater for that. I would suggest doing
```
{
  viewed: (logic goes here),
  ...input,
}
```
or changing the line to something like `viewed ?? (!!invite?.viewedAt ? undefined : true)`

2020-12-11 13:26 UTC, salemandreus commented on src/queries/queries.service.ts
> +        viewed: invite && !invite.viewedAt ? true : undefined,
Pushed the first change (Thanks for that I learned a bunch of useful things I didn't know before!)

Will follow up about the input.viewed to clarify that case with you.

2020-12-11 14:05 UTC, salemandreus commented on src/queries/queries.service.ts
> +        viewed: invite && !invite.viewedAt ? true : undefined,
Added in that case to catered for input.viewed now just needed to make sure I understood that properly.

2020-12-14 08:21 UTC, longtomjr requested changes

2020-12-14 08:21 UTC, longtomjr commented on src/queries/queries.service.ts
> +        viewed: input.viewed ?? (!!invite?.viewedAt ? undefined : true),
I don't think it makes sense to do both `input.viewed ??` and moving the input spread operator lower down. Please only do one.

2020-12-14 08:49 UTC, salemandreus commented on src/queries/queries.service.ts
> +        viewed: input.viewed ?? (!!invite?.viewedAt ? undefined : true),
Ah, right! 👍

2020-12-14 08:57 UTC, longtomjr approved these changes

2020-12-14 13:49 UTC, sabinebertram commented on src/queries/queries.service.ts
> +        viewed: input.viewed ?? (!!invite?.viewedAt ? undefined : true),
Just as a comment: I think this is not future-proof. It will set `viewed = true` on sending the invite once we add that functionality to core because it basically always sets it to `true` if it is undefined. 

I don't know how we should make sure we don't miss that when we add email sending @longtomjr .

2020-12-14 14:46 UTC, salemandreus commented on src/queries/queries.service.ts
> +        viewed: input.viewed ?? (!!invite?.viewedAt ? undefined : true),
@sabinebertram @longtomjr does this mean we are merging it in for now with a note to change it?
Can I merge it?

2020-12-14 14:48 UTC, longtomjr commented on src/queries/queries.service.ts
> +        viewed: input.viewed ?? (!!invite?.viewedAt ? undefined : true),
@salemandreus please hold off on merging until the discussion have been completed.

2020-12-14 14:51 UTC, longtomjr commented on src/queries/queries.service.ts
> +        viewed: input.viewed ?? (!!invite?.viewedAt ? undefined : true),
@sabinebertram sending `true` to the db-api sets the viewedAt timestamp. So from the perspective of this method, if the caller asked viewed: true, then this method should send it off with viewed: true. 

Maybe renaming this parameter to `updateViewedAt` or something will make it clearer what the db-api is doing, and what this method is doing in turn. 

We can do that as a separate task though, and add a refactor task for this, since it will have changes in core and query-db-api

2020-12-14 15:04 UTC, sabinebertram commented on src/queries/queries.service.ts
> +        viewed: input.viewed ?? (!!invite?.viewedAt ? undefined : true),
I think I'm thinking too much ahead here. I was assuming we'd use this `updateQueryInvite` also for setting the `sent` parameter in the query db and if we kept this line as is, it would also set `viewed` to the same timestamp, even if the student has not viewed yet. 

I just realized that we still have the `notify_student` method in the query api that sets `sent` so this would be a different function call from core anyways and wouldn't use `updateQueryInvite`. 

Please just let me know if my assessment is correct @longtomjr . 

And I agree that we should rename it at some point. Naming was never my strong suit.

2020-12-15 12:39 UTC, longtomjr commented on src/queries/queries.service.ts
> +        viewed: input.viewed ?? (!!invite?.viewedAt ? undefined : true),
@sabinebertram sounds good. I will create a ticket to look at the naming of these parameters.

The sent part would be different yes. From my perspective this function deals more with the student setting the status, rather than something else in the business process setting the status.

2020-12-15 12:59 UTC, sabinebertram approved these changes

2020-12-15 18:53 UTC, merged