Fix user scope rules #348
registreerocks/registree-core pull request #350
Opened 2021-01-19 22:56 UTC by PiDelport

Closes #348

2021-01-20 07:00 UTC, longtomjr requested changes
Just a couple of minor things

2021-01-20 08:37 UTC, PiDelport commented on src/rules.spec.ts
> +  // https://github.com/maticzav/graphql-shield/blob/master/tests/logic.test.ts
Good catch, thanks!

2021-01-20 08:46 UTC, PiDelport commented on src/rules.ts
> +      const scope = req?.user?.scope;
Cool. I wasn't sure what context guarantees we can actually rely on here without a runtime guard: I know that some GraphQL implementations may not supply the `user` for anonymous queries?

(I'm trying to find a reference about what's actually guaranteed in our case.)

2021-01-20 09:17 UTC, PiDelport commented on src/rules.ts
> +        (scope !== undefined && _scopeContains(scope, scopeToken)) ||
Hmm, I wanted to keep the check narrowed down to `undefined` from the `?.` operators to avoid swallowing an unexpected `null` scope here, but yeah, it's messy. A reusable helper to reliably get the user from scope would make sense here, and simplify the code.

2021-01-20 12:02 UTC, longtomjr commented on src/rules.ts
> +      const scope = req?.user?.scope;
@PiDelport The user is guaranteed since we add it to the request during authentication. [The gqlAuthMiddleware](https://github.com/registreerocks/registree-core/blob/staging/src/auth/gql-auth.middleware.ts#L8) (graphql middleware in this case) runs and use passport to validate the token, and adds the user to the request context. You can see where it is configured to run [in the graphql config of the app.module.ts](https://github.com/registreerocks/registree-core/blob/5a8612329044b5621d1ae9f10243e4086c5fd382/src/app.module.ts#L71-L75)

Any anonymous queries will fail because of the middleware since we require authentication before any query proceeds.

2021-01-20 12:08 UTC, longtomjr commented on src/rules.ts
> +        (scope !== undefined && _scopeContains(scope, scopeToken)) ||
If we are certain (and I am not sure on this) that scope is required for a valid user context, we might just want to error. I think we want the type-system to deal with this. If you remove the `.?` chaining, and the type is just `string` and not `string | null | undefined` (or just 2 of them) then we should not be doing a null check here.

We might want to change the `User` type however to match up with the standards if null/undefined is possible, but I would prefer if we create a task for that and action it separately from this PR.

2021-01-20 14:29 UTC, PiDelport commented
Okay, I tried a couple of things, and reworked this a bit.

I introduced a new `userFromContext` helper for checked access to the user from context. I refactored the code to use it, and also introduced it in the `@CurrentUser` decorator, which does the same kind of check.

The code is somewhat defensive, but it should be worth it here: if there's any misconfiguration, bug, or upstream issue in the auth middleware, a helpful error message and traceback from here will probably be very helpful.

2021-01-20 14:34 UTC, PiDelport commented on src/rules.ts
> +      const scope = req?.user?.scope;
Yup, the user should normally be there: the checks here are more defensive, in case of misconfiguration or bugs.

Better error reporting would definitely be good, though, yeah: see the https://github.com/registreerocks/registree-core/pull/350#issuecomment-763644012 update.

2021-01-20 14:36 UTC, PiDelport commented on src/rules.ts
> +        (scope !== undefined && _scopeContains(scope, scopeToken)) ||
The https://github.com/registreerocks/registree-core/pull/350#issuecomment-763644012 update should deal with this better.

2021-01-21 07:26 UTC, longtomjr requested changes
Just the one change and then we can get this merged.

2021-01-21 07:26 UTC, longtomjr commented on src/rules.ts
> +export function userFromContext(ctx: { req?: { user?: User } }): User {
Maybe rename this to `userFromGraphqlContext` or something similar. For helpers like this is makes sense to add it to a file in the src/common directory, or create a new file there if there is no relevant files available.

2021-01-21 07:30 UTC, PiDelport commented on src/rules.ts
> +export function userFromContext(ctx: { req?: { user?: User } }): User {
How about `userFromResolverContext`? (GraphQL has enough different types of contexts in code that it's useful for me to try and make it obvious which one.)

2021-01-21 07:35 UTC, longtomjr commented on src/rules.ts
> +export function userFromContext(ctx: { req?: { user?: User } }): User {
`userFromResolverContext` or `userFromGqlResolverContext` are both fine with me. I think I prefer the second one, but it is probably redundant to have `Gql` and `Resolver` (since resolver already indicates that we are likely working with graphql).

2021-01-21 07:42 UTC, PiDelport commented on src/rules.ts
> +export function userFromContext(ctx: { req?: { user?: User } }): User {
Cool, I like `Gql`. 😊️

(The "resolver context" still helps disambiguate it from the other types of context in GraphQL, but it should be fine to delegate that to the doc comment rather than the name, yeah.)

2021-01-21 08:43 UTC, PiDelport commented on src/rules.ts
> +export function userFromContext(ctx: { req?: { user?: User } }): User {
Alright, I moved the helper to `userFromGqlContext` under `common/graphql.helpers`: does that look good?

2021-01-21 08:44 UTC, longtomjr approved these changes

2021-01-21 08:45 UTC, PiDelport commented
Thanks!

2021-01-21 08:46 UTC, merged