Added a service for faculties and in the faculties resolver I added a query to get a single faculty by Id
registreerocks/registree-core pull request #380
Opened 2021-03-11 08:42 UTC by Nghondzweni

2021-03-16 12:40 UTC, longtomjr requested changes
Looks really nice and clean!

Only a minor consistency issue with the services.

2021-03-16 12:40 UTC, longtomjr commented on src/universities/faculies.service.ts
> +  async getFacultyById(facultyId: string): Promise<Faculty | null> {
All of the current service-level functionality is in the main service of a module. To keep with that pattern I think it will make sense to move this to the universities.service. 

I am happy to create a refactor task in the backlog to look at how we are currently doing it and refactoring to smaller services, but for now I think it makes sense to keep it consistent.

2021-03-16 12:43 UTC, longtomjr commented
Just another comment. It looks like the precommit hooks are not running on your side properly. We have hooks that check the format of the commit message using commit-lint, and make sure that committed code passed the linting and prettier constraints.

I am not sure what the issue could be, we can have a look at debugging and getting it set up.

2021-03-16 12:45 UTC, Nghondzweni commented on src/universities/faculies.service.ts
> +  async getFacultyById(facultyId: string): Promise<Faculty | null> {
I understand. I will do that just now. I initially thought about doing it that way but I was not sure.

2021-03-16 14:03 UTC, closed without merging

2021-03-18 01:27 UTC, PiDelport commented
(@Nghondzweni: Note that you don't have to create a new PR when updating a branch: continuing on this PR would have been fine. 🙂️)