refactor : moved faculty service-level fucnctionality into universities.service. also deleted faculties.service
registreerocks/registree-core pull request #381
Opened 2021-03-16 14:09 UTC by Nghondzweni

2021-03-17 08:04 UTC, longtomjr commented
see #380 for previous PR

2021-03-17 08:05 UTC, longtomjr approved these changes
Looks good!

2021-03-18 02:48 UTC, PiDelport commented
@Nghondzweni: I merged the commits together for history readability, and updated to commit message to be commitlint compatible.

2021-03-18 02:59 UTC, PiDelport requested changes
I added a test, which is currently failing in the `not found` case, but addressing the `NotFoundException` should make it pass.

2021-03-18 02:59 UTC, PiDelport commented on src/universities/resolvers/faculties.resolver.ts
> +    else throw new NotFoundException();
Using `NotFoundException` probably doesn't make sense here: it's specific to HTTP, and won't do something sensible in the context of GraphQL. (It will just be relayed to the client as a crash.)

The query result should probably be made nullable (by adding `{ nullable: true }` to the `@Query`).

2021-03-18 07:12 UTC, longtomjr commented on src/universities/resolvers/faculties.resolver.ts
> +    else throw new NotFoundException();
We should keep it consistent for what we currently have in this case. I think doing something like `      throw new ServerError('Failed to get faculty by id', err);` (what we currently do for the queries) is the best here. In the future we can look at doing nullable query results, but my preference is to just keep this as consistent as possible.

2021-03-18 07:23 UTC, PiDelport commented on src/universities/resolvers/faculties.resolver.ts
> +    else throw new NotFoundException();
Hmm, speaking of consistency, we should probably rename this to `getFaculty` too?

2021-03-18 20:50 UTC, Nghondzweni commented on src/universities/resolvers/faculties.resolver.ts
> +    else throw new NotFoundException();
I didn't actually see anywhere in the code where you guys resolve cases where an object is not found. Is that something that is done on the FE? 

Removing null from the return type on ```   async getFacultyById(facultyId: string): Promise<Faculty | null> {  ```  alows me to return the result and not have to worry about whether the faculty object was found or not.
Should I keep the null return type from there or thow the ServerError('Failed to get faculty by id', err) ?

2021-03-19 08:40 UTC, PiDelport commented on src/universities/resolvers/faculties.resolver.ts
> +    else throw new NotFoundException();
@Nghondzweni: Checking for the `null` and raising an exception should be good, yeah, like `QueryDataService.getQuery`.

We probably don't have great handling of missing results right now, but it's not really something that's part of the main app flow right now (the faculty data should remain be relatively constant in practice), so that's okay for now. 

So, summary:

- [ ] Rename `getFacultyById` → `getFaculty` (consistency)
- [ ] Raise `ServerError` instead of returning `null` (consistency)
- [ ] Update test to pass

2021-03-24 22:34 UTC, Nghondzweni commented on src/universities/resolvers/faculties.resolver.ts
> +    else throw new NotFoundException();
All changes requested on feedback summary completed.

2021-03-25 07:03 UTC, PiDelport approved these changes

2021-03-25 07:37 UTC, merged