feat: add messaging module to wrap nestjs-twilio
registreerocks/registree-core pull request #411
Opened 2022-02-09 10:37 UTC by billguo99

Resolves #406.

- [ ]     Update the event creation schema to include fields for what contact methods should be used, as well as the message that should be sent out.
- [WIP ]     Add a Twillio module that supports sending SMS ~~and Whatsapp~~ messages to a list of numbers.
- [ ]     After event creation, send messages to all of the cellphone numbers returned by the query-db-api using the twillio module.

Steps done:
1. `yarn add twilio nestjs-twilio`
2. Use nestjs cli to generate module and service for `messaging`
3. Add `twilio.config.ts` in config, to use `AppConfigService` to setup Twilio client in `MessagingModule`
4. Use customdirector @InjectTwilio to inject client into `MessagingService` and create simple `async sendSMS()` function

2022-02-10 11:54 UTC, billguo99 commented
Tested in GraphQL Playground 🎉
Mutation:
```
mutation{
  sendSMS(body: "Hi", to: "+27825893193")
}
```
Return:
```
{
  "data": {
    "sendSMS": "SM920c33ad3e8044fba8b1ff03e7f0ca90"
  }
}
```
ToDo:

- [ ] Convert/create the `sendSMS` functionality to be able to send to a list of numbers

2022-02-11 13:09 UTC, billguo99 commented
Working for list of numbers:
Mutation:
```
mutation{
  sendBulkSMS(message: "Testing duo numbers", numbers: ["+27765588901","+27825893193"])
}
```
Return:
```
{
  "data": {
    "sendBulkSMS": "SMbbef6c02daf9407aab82c03bb35277d5,SM9731072d7dd34ccdb092156e9aed0ab4"
  }
}
```

2022-02-16 09:38 UTC, longtomjr requested changes
Looks good. Just a minor change

2022-02-16 09:38 UTC, longtomjr commented on src/query-data/dto/query.response.ts
> +  smsMessage: string;
The query-data service will not have a smsMessage that it returns. We should remove this field.

2022-02-16 10:41 UTC, longtomjr approved these changes
Looks good thanks!

2022-02-16 11:00 UTC, merged